### ISSUE TITLE
Form Builder: Unable to set Form Name and Version

### ISSUE THREAD

**Issue by gracepotma** [openmrs/openmrs-esm-form-builder#127]
(Posting on behalf of @mogoodrich from PIH)
In the "Save form to server" modal, the "Form Name"  and "Version" fields are uneditable for some reason.  This is a new issue, not sure if it's possibly caused by something introduced in [O3-2124](https://issues.openmrs.org/browse/O3-2124).

I was able to reproduce on dev3 and on my local dev environment.

See screenshot below (the fields look editable, but I am unable to make changes to them.

![2023-05-22_17-43](https://github.com/openmrs/openmrs-esm-form-builder/assets/67400059/033cbb11-40c3-4501-a17e-a8cf75d20313)

**Comment by Prajwaldindokar5** [comment]
there is no error , i am able to set name and version in my dev enviornment

**Comment by sherrif10** [comment]
Hello @denniskigen  , Can you comfirm this is an issue still, @Prajwaldindokar5  is not encountering the same issue. Thanks.
