### ISSUE TITLE
Remove "conceptMappings" from dummy form schema

### ISSUE THREAD

**Issue by mogoodrich** [openmrs/openmrs-esm-form-builder#130]
The dummy schema from provided by the form builder includes "conceptMapping" fields, ie:

```
"questions": [
            {
              "label": "Another Question of type obs whose answers get rendered as radio inputs",
              "type": "obs",
              "questionOptions": {
                "rendering": "radio",
                "concept": "system-defined-concept-uuid",
                "answers": [
                  {
                    "concept": "another-system-defined-concept-uuid",
                    "label": "Choice 1",
                    "conceptMappings": []
                  },
                  {
                    "concept": "yet-another-system-defined-concept-uuid",
                    "label": "Choice 2",
                    "conceptMappings": []
                  },
                  {
                    "concept": "yet-one-more-system-defined-concept-uuid",
                    "label": "Choice 3",
                    "conceptMappings": []
                  }
                ]
              },
              "id": "anotherSampleQuestion"
            }
```

These "conceptMappings" fields are currently ignored (and probably always will be) so we should remove them from the dummy schema to avoid confusion.

fyi @denniskigen  @samuelmale

**Comment by samuelmale** [comment]
@mogoodrich Assuming support for "concept mappings" is a priority for orgs like PIH for an MVP, I'm inclined to keep them considering that we may introduce this support very soon.

**Comment by mogoodrich** [comment]
@samuelmale  for concept mapping support, we'd want to be able to unqiuely reference a concept by mapping and source **instead of** uuid, so I think we'd want to use the concept field for this, ie support:

```
answers": [
                  {
                    "concept": "CIEL:1234",
                    "label": "Choice 1"
                  },

```

We could consider using a mapping field *instead* of a concept field, like:

``
answers": [
                  {
                    "conceptMapping": "CIEL:1234",
                    "label": "Choice 1"
                  },
```

But I don't see a case where we'd want to ever specify multiple mappings or use an array.

**Comment by samuelmale** [comment]
Makes perfect sense @mogoodrich!

**Comment by hadijahkyampeire** [comment]
@samuelmale are you tracking this issue and working on it?

**Comment by samuelmale** [comment]
No @hadijahkyampeire, I'm not. Feel free to take it up.
