### ISSUE TITLE
In GUI builder, add abilitiy to reference concept by source/mapping pair

### ISSUE THREAD

**Issue by mogoodrich** [openmrs/openmrs-esm-form-builder#155]
In the Form Builder GUI, you are able to look up a concept and add it to a form.  In the underlying form schema, this concept is referenced by uuid, because that was the only supported way to reference a concept.

Now that we support referenced a concept by source and mapping pair, it would be great for a user to be able to select the a mapping from the list presented in the UI and then have the form builder use that source/mapping pair here:

![2023-06-21_11-02](https://github.com/openmrs/openmrs-esm-form-builder/assets/1163015/dcc99563-b523-4fed-b396-1fb6dbc269af)

**Comment by chyroshan066** [comment]
I’m interested in working on this issue if it’s still relevant.

**Comment by NethmiRodrigo** [comment]
Created a ticket for this

**Comment by chyroshan066** [comment]
> Created a ticket for this

Thanks! Could you link the ticket here if possible so I can follow along?
