### ISSUE TITLE
Enhance error handling in ActionButtons component

### ISSUE THREAD

**Issue by malak-elbanna** [openmrs/openmrs-esm-form-builder#234]
When an exception is thrown, the "ActionButtons" component currently sets the status to 'error'. It doesn't provide UI indication of recovery options for the user. The user should be informed with an appropriate message and have the option to retry the operation, which serves the goal of a better user experience.

**Comment by joellui** [comment]
Hi Malak,

I would love to work on this issue, 
Can you please provide me with some details,  like how can i replicated this situation, and what should the UI look like . 
PS I am new to this so will ask a lot of unusual questions. :)

**Comment by chyroshan066** [comment]
I’m interested in working on this issue if it’s still relevant.
