### ISSUE TITLE
Enhance loading state UI in Form Renderer Component

### ISSUE THREAD

**Issue by malak-elbanna** [openmrs/openmrs-esm-form-builder#237]
The current loading state in the "Form Renderer" component is a simple text message. This minimalistic approach may not be engaging enough for users especially if the loading takes a lot of time. If the loading state was more interactive, it would improve the UX and would be more visually appealing.

**Comment by Prateek579** [comment]
Hi @malak-elbanna   I would love to work on this issue. Would you please assign this to me.

**Comment by chyroshan066** [comment]
I’m interested in working on this issue if it’s still relevant.
