### ISSUE TITLE
Enhance the handling of the "formHasResources" condition in the useClobdata hook

### ISSUE THREAD

**Issue by malak-elbanna** [openmrs/openmrs-esm-form-builder#239]
Currently, the condition checks several aspects of the "form" object to identify if the URL should be constructed and whether the fetch should occur or not. However, this might lead to unnecessary complexity and potential errors if the "form" object structure changes or if the "name" of the resource isn't 'JSON schema'.

**Comment by vishisht-dubey** [comment]
hii @malak-elbanna can i work on this?? would you please assign this to me

**Comment by malak-elbanna** [comment]
> hii @malak-elbanna can i work on this?? would you please assign this to me

hi  @vishisht-dubey ! I'm a contributor, so I'm afraid I can't help you in this. I think you might need to refer to one of the repo maintainers!

**Comment by chyroshan066** [comment]
Hi, I’d like to work on this issue. Could I be assigned?
