### ISSUE TITLE
Add Field Type 'Submit'

### ISSUE THREAD

**Issue by ckote** [openmrs/openmrs-esm-form-builder#62]
{
          "type": "submit",
          "text": {
            "type": "plain_text",
            "text": "submit"
          }
        }

**Comment by Itsbabin** [comment]
Hi, I want to work on this issue. can you please tell me the actual issue?

**Comment by Anshul439** [comment]
Is someone still working on this issue?

**Comment by chyroshan066** [comment]
I’m interested in working on this issue if it’s still relevant.
