### ISSUE TITLE
Subforms/Referenced Forms Functionality

### ISSUE THREAD

**Issue by ckote** [openmrs/openmrs-esm-form-builder#80]
The current engine has documentation on this but the feature is not supported and the engine is not able to display or render this feature. @donaldkibet

**Comment by donaldkibet** [comment]
Yes @samuelmale had a proposal on how this should be done. Will be exploring this in the morning

**Comment by gracepotma** [comment]
How is it going re. Subforms support? 
4 PIH team members expressed on today's Design Call that this is useful functionality for them too. FYI @mogoodrich

**Comment by samuelmale** [comment]
Hi @gracepotma 

Subforms support was rejuvenated and we believe it now works out of the box!

**Comment by gracepotma** [comment]
Great to hear @samuelmale! _Believe_ it works, or _know_ it works? ;) ;)  @ckote is your team of BAs unblocked?

**Comment by NethmiRodrigo** [comment]
Closing this as it has been ticketed
